# Generated by Django 2.2.3 on 2019-09-11 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHAESTADO', models.DateField()),
                ('DESCRIPCION', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ULTIMASESION', models.DateField()),
                ('FECHAAUDITORIA', models.DateField()),
                ('ESTATUS', models.CharField(max_length=25)),
                ('ACCION', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=50)),
                ('DIRECCION', models.CharField(max_length=50)),
                ('TELEFONO', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cupones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHACUPON', models.DateField()),
                ('DESCRIPCION', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCUENTO', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetallePromocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=50)),
                ('TIPO', models.CharField(max_length=50)),
                ('DESCRIPCION', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Farmacias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=100)),
                ('DIRECCION', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CANTIDAD', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NotasdeCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHANC', models.DateField()),
                ('MONTO', models.IntegerField()),
                ('BANCO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actors.Bancos')),
                ('FARMACIA', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actors.Farmacias')),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('ID', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('PRIMERNOMBRE', models.CharField(max_length=20)),
                ('SEGUNDONOMBRE', models.CharField(max_length=20)),
                ('APELLIDOS', models.CharField(max_length=40)),
                ('CEDULA', models.CharField(max_length=15)),
                ('TELEFONO', models.CharField(max_length=25)),
                ('DIRECCION', models.CharField(max_length=25)),
                ('GENERO', models.CharField(max_length=25)),
                ('FECHANACIMIENTO', models.DateField()),
                ('CORREO', models.EmailField(max_length=100, unique=True)),
                ('VERIFICACIONCORREO', models.BooleanField(default=False)),
                ('FOTOPERFIL', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRIPCION', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHACREACION', models.DateField()),
                ('DESCRIPCION', models.CharField(max_length=250)),
                ('ESTATUS', models.BooleanField(default=False)),
                ('FECHAVIGENCIA', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FOTORECETA', models.CharField(max_length=100)),
                ('FECHAFOTO', models.DateField()),
                ('SEGUNDONOMBRE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Promocion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoNC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPO', models.CharField(max_length=50)),
                ('DESCRIPCION', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TiposAutenticaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPO', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=25)),
                ('PASSWORD', models.CharField(max_length=25)),
                ('FECHACREACION', models.DateField()),
                ('ESTADO', models.BooleanField(default=False)),
                ('AUTENTICACION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.TiposAutenticaciones')),
                ('PERSONA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Personas')),
            ],
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.AddField(
            model_name='notasdecredito',
            name='PROMOCION',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actors.Promocion'),
        ),
        migrations.AddField(
            model_name='notasdecredito',
            name='TIPONC',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actors.TipoNC'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='PRODUCTO',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actors.Productos'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='PROMOCION',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actors.Promocion'),
        ),
        migrations.AddField(
            model_name='detallepromocion',
            name='PRODUCTO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Productos'),
        ),
        migrations.AddField(
            model_name='detallepromocion',
            name='PROMOCION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Promocion'),
        ),
        migrations.AddField(
            model_name='detallecupon',
            name='PRODUCTO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Productos'),
        ),
        migrations.AddField(
            model_name='cupones',
            name='ESTADO',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actors.Estados'),
        ),
        migrations.AddField(
            model_name='cupones',
            name='FARMACIA',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actors.Farmacias'),
        ),
        migrations.AddField(
            model_name='cupones',
            name='NOTACREDITO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.NotasdeCredito'),
        ),
        migrations.AddField(
            model_name='cupones',
            name='PERSONA',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actors.Personas'),
        ),
        migrations.AddField(
            model_name='cupones',
            name='RECETA',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actors.Recetas'),
        ),
        migrations.AddField(
            model_name='auditoriausuarios',
            name='USUARIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Usuarios'),
        ),
        migrations.AddField(
            model_name='auditoriacupon',
            name='CUPON',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Cupones'),
        ),
        migrations.AddField(
            model_name='auditoriacupon',
            name='ESTADO',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actors.Estados'),
        ),
        migrations.AddField(
            model_name='auditoriacupon',
            name='USUARIO',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actors.Usuarios'),
        ),
    ]
